add folder structure for navbar and footer
Squeryll/Squeryll-Website pull request #4
Opened 2023-03-15 20:53 UTC by BIKRAM-SAHA

Solves issue: #2 
changes made:
added files Navbar.tsx, Navbar.module.scss, Navbar.types.ts
added files Footer.tsx, Footer.module.scss, Footer.types.ts

2023-03-17 16:17 UTC, FaizBShah requested changes

2023-03-17 16:17 UTC, FaizBShah commented on components/commons/footer/Footer.tsx
> +export default function Footer({}: FooterProps) {
`FC` stands for FunctionalComponent Type, which is a type provided by React for Functional Components

```suggestion
const Footer: FC<Props> = ({}) => {
```

2023-03-17 16:17 UTC, FaizBShah commented on components/commons/footer/Footer.tsx
> +import { FooterProps } from "./Footer.types";
import `FC` from `react` in the code

2023-03-17 16:17 UTC, FaizBShah commented on components/commons/footer/Footer.tsx
> +}
Add `export default Footer;` at the end

2023-03-17 16:17 UTC, FaizBShah commented on components/commons/footer/Footer.tsx
> +import { FooterProps } from "./Footer.types";
```suggestion
import { FooterProps as Props } from "./Footer.types";
```

2023-03-17 16:17 UTC, FaizBShah commented on components/commons/navbar/Navbar.tsx
Same changes for `Navbar.tsx` file as `Footer.tsx`

2023-03-17 16:17 UTC, FaizBShah commented on components/commons/footer/Footer.tsx
> +import "./styles/Footer.module.scss";
```suggestion
import styles from "./styles/Footer.module.scss";
```

2023-03-17 18:38 UTC, BIKRAM-SAHA commented
Done the changes in the new commit. Can you please review again?

2023-03-18 13:53 UTC, FaizBShah approved these changes
LGTM

2023-03-18 13:53 UTC, merged